/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lrqsxlvcwxqpcgjlerus"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxycXN4bHZjd3hxcGNnamxlcnVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMTgxMzIsImV4cCI6MjA4MDc5NDEzMn0.9Az-a7Ry3w-cGVbCLKwSz5kOAW-nJRGGepGkHbitCTY"